### PR TITLE
remove yaml support + fix config flow options

### LINKED ISSUE #89: [bug]: Changing options is not working correctly
can not modify the height, weight and Impedance options on the GUI

### PR DESCRIPTION
**Pull request by edenhaus**
- Removes the previously deprecated yaml support **BREAKING CHANGE**, therefore I suggest version v3
- Fixes some bug with the config flow:
  - Update entities if we change the setting via Option Handler. Fixes #89 
  - Use values from Options Handler
  - Add "already_configured" error to translations
- Sort all json files

@dckiller51 I would suggest, that we release v3 together with #75, after I have finish it. Takes me probably another week

### CODE REVIEW

**Comment by dckiller51** [comment]
I just did the tests. It works well. I'll just have to make an update for the FR traction.

**Comment by dckiller51** [comment]
@edenhaus 
Hello, have you finalized your update?

**Comment by edenhaus** [comment]
@dckiller51 I still need to convert the body score to the new format in #75 but than I'm ready. Sorry but I had this month real life problems and they have priority, but I hope I can finish it next week. I will merge this PR as I need it in #75, but don't release a version yet as we should include #75 in the new version

**Comment by dckiller51** [comment]
No problem you are right personal life is most important. Good luck in your difficult times.

**Pull request merged**
