### PR TITLE
use text selector with type date instead of date selector

### LINKED ISSUE #76: V2.1.0 no input for Birthday "apple iOS"
no input field for birthday

Bildschirmfoto 2022-04-13 um 12 57 54

### LINKED ISSUE #78: Date picker don't allow to select a date before 01.01.1970
I can not pick my birthdate because I was born before 1970... Date picker does not go further back then 01-01-1970?

_Originally posted by @lazodar in https://github.com/dckiller51/bodymiscale/issues/76#issuecomment-1099123083_

### PR DESCRIPTION
**Pull request by edenhaus**
Fixes #76
Fixes #78 

Tested on:
- Firefox on Manjaro
- Safari on iPad Air with 15.4.1
- Chrome on Android 11

### CODE REVIEW

**Comment by edenhaus** [comment]
@dckiller51 and everyone: Can you also please test it on your devices?

**Comment by dckiller51** [comment]
> @dckiller51 and everyone: Can you also please test it on your devices?

I just tested. It's perfect. 
Ipad iOS12.5.5 with safari = ok
Windows Chrome PC = ok
Android with Home Assistant app = ok

**Comment by dckiller51** [comment]
@edenhaus Hello, if you are happy with my minor changes we can push the update.

**Comment by edenhaus** [comment]
I will test it on an Iphone this afternoon. Only to be sure and then I will merge and release it 😊

**Comment by edenhaus** [comment]
Its also working on the iphone

**Pull request merged**
