### PR TITLE
add config flow

### LINKED ISSUE #39: No Unique ID
Please add a unique ID to the Entity generated.

image

### PR DESCRIPTION
**Pull request by edenhaus**
This PR add support for the config flow and deprecated the configuration in yaml.
On startup the yaml config will be imported and the user will be advised to delete the yaml config.

As this is not a breaking change I will suggest version `2.1.0`

Minimum required HA version is 2022.04, but hacs will only show the update if you are running at least this version. If someone has installed it manually, he will get an error message, if his HA version is not supported.

Also updated the dependencies, so the PR of the dependabot will be closed automatically after this is merged.

Fixes #39

### CODE REVIEW

**Comment by edenhaus** [comment]
@dckiller51 Can you please setup https://github.com/marketplace/pre-commit-ci It's free for public repos and will automatically checks the pre-commit checks on each push. Thanks :)

**Comment by dckiller51** [comment]
> [pre-commit-ci](https://github.com/marketplace/pre-commit-ci)

Hello, I can't wait to test your update. I think I installed pre-commit-ci here and on the card. Can you check ? This allows you to access and automatically push updates? Sorry I'm new to github. I did everything on self-taught.

**Comment by edenhaus** [comment]
I have added the pre-commit file in the last PR. You only need to activate the action, that it will be runned automatically on github 😊

**Comment by edenhaus** [comment]
Forgotten to answer the first question: @dckiller51 It not installed yet

**Comment by dckiller51** [comment]
> J'ai oublié de répondre à la première question : @dckiller51 Il n'est pas encore installé

Ah okay, I validate in the minutes.😉

**Pull request merged**
