### PR TITLE
Subscribe to correct handler

### LINKED ISSUE #101: Bug in weight sensor after update 3.0.0
Dear Developer,

After update to latest version, new weight sensor is updating for all “accounts” in integration. I have 3 person in there, and if I update weight for one of them, rest 2 updates same way with same weight. Have to roll back to version before 2.1.1. 

BRGDS

Alex

### PR DESCRIPTION
**Pull request by edenhaus**
Fix #101

### CODE REVIEW

**Comment by edenhaus** [comment]
@dckiller51 I have created two more sensor to test multiple config entries in the future

**Comment by edenhaus** [comment]
@dckiller51 fixed the KeyError can you retest it?

**Comment by dckiller51** [comment]
> @dckiller51 fixed the KeyError can you retest it?

It's OK. The ideal weight is again with a lot of decimals.

**Comment by dckiller51** [comment]
> > @dckiller51corrigé le KeyError pouvez-vous le retester?
> 
> C'est bon. Le poids idéal est à nouveau avec beaucoup de décimales.

Can you put the age on Attributs ?

**Comment by edenhaus** [comment]
> The ideal weight is again with a lot of decimals.

That should not be possible. See the code...
https://github.com/dckiller51/bodymiscale/blob/2f840ba3863ba385e9de2228181acbeb59d79356/custom_components/bodymiscale/util.py#L26

Can you please share your config

**Comment by dckiller51** [comment]
> > The ideal weight is again with a lot of decimals.
> 
> That should not be possible. See the code...
> 
> https://github.com/dckiller51/bodymiscale/blob/2f840ba3863ba385e9de2228181acbeb59d79356/custom_components/bodymiscale/util.py#L26
> 
> Can you please share your config

Sorry I was not up to date on this file.

**Comment by edenhaus** [comment]
@dckiller51 No Problem. Can you please merge it and release a bug fix version

**Pull request merged**
